export const SET_USER_NAME = 'SET_USER_NAME';


export const SET_GEOLOCATION = 'SET_GEOLOCATION';
export const SET_GEOLOCATION_ERROR = 'SET_GEOLOCATION_ERROR';


export const RESET_METADATA = 'RESET_METADATA';


export const ADD_LOCATION = 'ADD_LOCATION';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const SAVE_LOCATION_PENDING = 'SAVE_LOCATION_PENDING';
export const SAVE_LOCATION_SUCCESS = 'SAVE_LOCATION_SUCCESS';
export const SAVE_LOCATION_FAILURE = 'SAVE_LOCATION_FAILURE';


export const SET_STATE_UPDATE = 'SET_STATE_UPDATE';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';


export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';


export const FETCH_LOCATIONS_REQUEST = 'FETCH_LOCATIONS_REQUEST';
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS';
export const FETCH_LOCATIONS_FAILURE = 'FETCH_LOCATIONS_FAILURE';

export const UPDATE_MODE_EDIT = 'UPDATE_MODE_EDIT';
